name: Continuos Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - 'aws'

jobs:
  continuos_delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validação resultado do PR
        id: check_merge
        run: | #essa run impede o deploy caso o workflow acabe ativando mesmo com o PR negado
          if [[ "${{ github.event.pull_request.merged }}" != "true" ]]; then
            echo "Pull request was not merged. Exiting."
            exit 1
          fi

      - name: Login Docker Hub
        if: steps.check_merge.outcome == 'success'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up JDK 17
        if: steps.check_merge.outcome == 'success'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        if: steps.check_merge.outcome == 'success'
        run: |
          mvn clean package
          ls -l target/
          mv target/*.jar target/terabite.jar
          ls -l target/

      - name: Build and push Docker image
        run: |
          docker build -t integracaosistema/mestresorvete-backend-api:latest .
          docker push integracaosistema/mestresorvete-backend-api:latest

  continuos_deployment:
    runs-on: back-01
    steps:
      - name: Environment tests
        run: |
          java -version
          sudo docker --version

      - name: Update and restart application
        run: |
          sudo docker pull integracaosistema/mestresorvete-backend-api:latest
          sudo docker stop terabite-backend-api || true
          sudo docker rm terabite-backend-api || true
          sudo docker run -d --name terabite-backend-api --env-file .env -p 8080:8080 integracaosistema/mestresorvete-backend-api:latest

      - name: Final check
        run: sudo docker ps -a
