name: Continuos Integration

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'aws'
      - 'cicdtests2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build with Maven
        run: mvn -B package -DskipTests